linters:
  enable:
    - errcheck
    - cyclop
    - goconst
linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0.0
    skip-tests: false
  goconst:
    min-len: 3
    min-occurrences: 3
