// Code generated by MockGen. DO NOT EDIT.
// Source: meegle-cli/internal/screen (interfaces: AppModel)
//
// Generated by this command:
//
//	mockgen -destination=internal/screen/mock/mock_appmodel.go -package=mock meegle-cli/internal/screen AppModel
//

// Package mock is a generated GoMock package.
package mock

import (
	meegle "meegle-cli/internal/meegle"
	screen "meegle-cli/internal/screen"
	store "meegle-cli/internal/store"
	reflect "reflect"

	tea "github.com/charmbracelet/bubbletea"
	gomock "go.uber.org/mock/gomock"
)

// MockAppModel is a mock of AppModel interface.
type MockAppModel struct {
	ctrl     *gomock.Controller
	recorder *MockAppModelMockRecorder
	isgomock struct{}
}

// MockAppModelMockRecorder is the mock recorder for MockAppModel.
type MockAppModelMockRecorder struct {
	mock *MockAppModel
}

// NewMockAppModel creates a new mock instance.
func NewMockAppModel(ctrl *gomock.Controller) *MockAppModel {
	mock := &MockAppModel{ctrl: ctrl}
	mock.recorder = &MockAppModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppModel) EXPECT() *MockAppModelMockRecorder {
	return m.recorder
}

// MeegleCmds mocks base method.
func (m *MockAppModel) MeegleCmds() *meegle.Cmds {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeegleCmds")
	ret0, _ := ret[0].(*meegle.Cmds)
	return ret0
}

// MeegleCmds indicates an expected call of MeegleCmds.
func (mr *MockAppModelMockRecorder) MeegleCmds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeegleCmds", reflect.TypeOf((*MockAppModel)(nil).MeegleCmds))
}

// NextReqID mocks base method.
func (m *MockAppModel) NextReqID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextReqID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// NextReqID indicates an expected call of NextReqID.
func (mr *MockAppModelMockRecorder) NextReqID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextReqID", reflect.TypeOf((*MockAppModel)(nil).NextReqID))
}

// Pop mocks base method.
func (m *MockAppModel) Pop() tea.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop")
	ret0, _ := ret[0].(tea.Cmd)
	return ret0
}

// Pop indicates an expected call of Pop.
func (mr *MockAppModelMockRecorder) Pop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockAppModel)(nil).Pop))
}

// ProjectKey mocks base method.
func (m *MockAppModel) ProjectKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// ProjectKey indicates an expected call of ProjectKey.
func (mr *MockAppModelMockRecorder) ProjectKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectKey", reflect.TypeOf((*MockAppModel)(nil).ProjectKey))
}

// Push mocks base method.
func (m *MockAppModel) Push(arg0 screen.Screen) tea.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0)
	ret0, _ := ret[0].(tea.Cmd)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockAppModelMockRecorder) Push(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockAppModel)(nil).Push), arg0)
}

// Replace mocks base method.
func (m *MockAppModel) Replace(arg0 screen.Screen) tea.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", arg0)
	ret0, _ := ret[0].(tea.Cmd)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockAppModelMockRecorder) Replace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockAppModel)(nil).Replace), arg0)
}

// StoreState mocks base method.
func (m *MockAppModel) StoreState() store.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreState")
	ret0, _ := ret[0].(store.State)
	return ret0
}

// StoreState indicates an expected call of StoreState.
func (mr *MockAppModelMockRecorder) StoreState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreState", reflect.TypeOf((*MockAppModel)(nil).StoreState))
}
